// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return android; // fall back to android options
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcL8AJHZKPEGcKgiQv3fWDFf5gBAwWUCM',
    appId: '1:1007222142821:web:7061f43cc07bd56542138c',
    messagingSenderId: '1007222142821',
    projectId: 'petco-6301a',
    authDomain: 'petco-6301a.firebaseapp.com',
    storageBucket: 'petco-6301a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVzOM5pARz6FFVDMejR9rUIecIVIL7U7Y',
    appId: '1:1007222142821:android:5bb261c2db35a46c42138c',
    messagingSenderId: '1007222142821',
    projectId: 'petco-6301a',
    storageBucket: 'petco-6301a.firebasestorage.app',
  );

}